# Generated by Django 6.0.4 on 2026-04-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('proteina', 'Proteína'), ('carbohidrato', 'Carbohidrato'), ('grasa', 'Grasa'), ('verdura', 'Verdura'), ('otro', 'Otro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('condicion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('tipo', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Once', 'Once'), ('Cena', 'Cena'), ('Colacion', 'Colación')], max_length=10)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.alimento')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepta', models.BooleanField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.alimento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.persona')),
            ],
        ),
    ]
