# Generated by Django 6.0.4 on 2026-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='acepta',
            field=models.BooleanField(default=False, verbose_name='Acepta este alimento'),
        ),
    ]
