# Generated by Django 6.0.4 on 2026-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_alter_preferencia_acepta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusemanal',
            name='plato',
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='platos',
            field=models.ManyToManyField(to='nutricion.plato'),
        ),
    ]
