# Generated by Django 6.0.4 on 2026-04-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_remove_menusemanal_plato_menusemanal_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('fondo', 'Fondo'), ('ensalada', 'Ensalada'), ('bebestible', 'Bebestible')], default='fondo', max_length=20),
            preserve_default=False,
        ),
    ]
