# Generated by Django 6.0.4 on 2026-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_plato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Principal'), ('acompanamiento', 'Acompañamiento'), ('bebida', 'Bebida'), ('fruta', 'Fruta'), ('snack', 'Snack')], max_length=20),
        ),
    ]
