# Generated by Django 6.0.4 on 2026-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0005_alter_plato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='azucar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='carbohidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='energia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='grasas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='sodio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
