# Generated by Django 6.0.4 on 2026-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0006_alimento_azucar_alimento_carbohidratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad_gramos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
